# We like to use pre-commit but we prefer not to combine pre-commit/psf-black
# fixes with the commit step.  Instead, we block pushes until things get fixed.
#
# pre-commit install --hook-type pre-push
# by hand, that comes out to something like this:
# pre-commit run --from-ref upstream/master --to-ref HEAD
#
# but do whatever you like

fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: ['--line-length', '119']

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: ./pathed-pylintest pylint
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: ./pathed-pylintest pytest t --cov sudoku --cov-report term-missing:skip-covered --no-cov-on-fail --cov-fail-under 100
        always_run: true
        language: system
        pass_filenames: false
