#!/usr/bin/env python
# coding: utf-8

import logging
logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger('ipy')

from glob import glob
from sudoku import solve

def reload_puzzles():
    global P, A
    from sudoku import get_puzzles
    P = list(get_puzzles())
    A = list()

    for file in glob('t/asset/p*.txt'):
        A.extend(get_puzzles(file))

reload_puzzles()
fp = P[0]
fq = solve(fp)

lp = P[-1]
lq = solve(lp)

p = P[9]
q = solve(p)
q.check()
