#!/usr/bin/env python
# coding: utf-8

import os
import logging

from glob import glob
from sudoku import solve
from sudoku.const import ELEMENT_VALUES as EV
from sudoku import get_puzzles

log = logging.getLogger('ipy')

def sorta_true(X):
    if isinstance(X, str):
        if X.lower() in ('t', 'true', 'y', 'yes'):
            return True
        if X.lower() in ('f', 'false', 'n', 'no'):
            return False
        try:
            x = int(X)
            if x == 0:
                return False
            return True
        except ValueError:
            pass
    return bool(X)

def maybe_solve(p):
    if sorta_true(os.environ.get("NO_SOLVE")):
        return p
    if so := os.environ.get("SOLVE_ONLY"):
        for item in so.split():
            try:
                item = int(item)
                if P[item] is p:
                    return solve(p)
            except ValueError:
                pass
        return p
    return solve(p)

def reload_puzzles():
    global P, Q
    P = list(get_puzzles())

    global last_puzzle
    last_puzzle = len(P)-1

    for file in glob('t/asset/p*.txt'):
        bname = os.path.basename(file)[:-4]
        P.extend(get_puzzles(file))

    for i,p in enumerate(P):
        globals()[f'p{i}'] = p

    L = len(P)
    Q = [ maybe_solve(p) for i,p in enumerate(P) ]

    for i,q in enumerate(Q):
        globals()[f'q{i}'] = q

    log.debug("loaded %d puzzles in 'P' and 'p0' … 'pN'", len(P))
    log.debug("loaded %d corresponding solutions in 'Q' and 'q0' … 'qN'", len(Q))

    for i in reversed(range(3)):
        a = last_puzzle - i
        log.debug("pm%d/qm%d => p%d/q%d", i, i, a, a)
        globals()[f'pm{i}'] = P[a]
        globals()[f'qm{i}'] = Q[a]

reload_puzzles()
