#!/usr/bin/env python
# coding: utf-8

from sudoku import solve

def reload_puzzles():
    from sudoku import get_puzzles
    global p, q
    p = list(get_puzzles())
    q = list(solve(x) for x in p)

reload_puzzles()
